// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLEp2BXFxzt-f-5YhqauQwEQf0JQ94BSM',
    appId: '1:420014344117:web:445c064bb75b1deab7fbfc',
    messagingSenderId: '420014344117',
    projectId: 'assesment-5f173',
    authDomain: 'assesment-5f173.firebaseapp.com',
    storageBucket: 'assesment-5f173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBin9DPGddNbuuGQLQR1CWUXf8cjYm9r24',
    appId: '1:420014344117:android:ff7147a74b6f7084b7fbfc',
    messagingSenderId: '420014344117',
    projectId: 'assesment-5f173',
    storageBucket: 'assesment-5f173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Pk_d0IwjIpSj5sZJqAgy0qqY2Ph7JmM',
    appId: '1:420014344117:ios:ff72d76c22208adab7fbfc',
    messagingSenderId: '420014344117',
    projectId: 'assesment-5f173',
    storageBucket: 'assesment-5f173.appspot.com',
    iosBundleId: 'com.example.assesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Pk_d0IwjIpSj5sZJqAgy0qqY2Ph7JmM',
    appId: '1:420014344117:ios:f807b43775df13bdb7fbfc',
    messagingSenderId: '420014344117',
    projectId: 'assesment-5f173',
    storageBucket: 'assesment-5f173.appspot.com',
    iosBundleId: 'com.example.assesment.RunnerTests',
  );
}
